// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjxeSG4UkJxehkg54N7I1NFe9lIJtPpWs',
    appId: '1:131944045486:web:0c81ab928f15f709e1863f',
    messagingSenderId: '131944045486',
    projectId: 'bs-base-2325',
    authDomain: 'bs-base-2325.firebaseapp.com',
    storageBucket: 'bs-base-2325.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsKKhpdTcNIoJyIBrW37X15SIeoiUOrF0',
    appId: '1:131944045486:android:adb3295d81b79fabe1863f',
    messagingSenderId: '131944045486',
    projectId: 'bs-base-2325',
    storageBucket: 'bs-base-2325.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB-JzSCX7JoWCWBiySJLhNw8bgM0pZ8l0',
    appId: '1:131944045486:ios:2000cfad2f59fa09e1863f',
    messagingSenderId: '131944045486',
    projectId: 'bs-base-2325',
    storageBucket: 'bs-base-2325.firebasestorage.app',
    iosBundleId: 'com.example.proyectobase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB-JzSCX7JoWCWBiySJLhNw8bgM0pZ8l0',
    appId: '1:131944045486:ios:2000cfad2f59fa09e1863f',
    messagingSenderId: '131944045486',
    projectId: 'bs-base-2325',
    storageBucket: 'bs-base-2325.firebasestorage.app',
    iosBundleId: 'com.example.proyectobase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjxeSG4UkJxehkg54N7I1NFe9lIJtPpWs',
    appId: '1:131944045486:web:0de9dd76ed82ae0ce1863f',
    messagingSenderId: '131944045486',
    projectId: 'bs-base-2325',
    authDomain: 'bs-base-2325.firebaseapp.com',
    storageBucket: 'bs-base-2325.firebasestorage.app',
  );
}
