// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsTc5nXkIDyKhdhRn-jVulbJm5afWg4dY',
    appId: '1:15684248875:web:ba805a20adef018765d16e',
    messagingSenderId: '15684248875',
    projectId: 'appmovil-8',
    authDomain: 'appmovil-8.firebaseapp.com',
    storageBucket: 'appmovil-8.firebasestorage.app',
    measurementId: 'G-85E11SZJ3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJPZEzXSl_uvnaLxZW9uyQ08ORREIwwSA',
    appId: '1:15684248875:android:f29710dfc4de214465d16e',
    messagingSenderId: '15684248875',
    projectId: 'appmovil-8',
    storageBucket: 'appmovil-8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe-_geQuXEhUdVYN_C9YJZFyyqHMCP3hI',
    appId: '1:15684248875:ios:4de7ada48f5f0dec65d16e',
    messagingSenderId: '15684248875',
    projectId: 'appmovil-8',
    storageBucket: 'appmovil-8.firebasestorage.app',
    iosBundleId: 'com.example.appmovilpractica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe-_geQuXEhUdVYN_C9YJZFyyqHMCP3hI',
    appId: '1:15684248875:ios:4de7ada48f5f0dec65d16e',
    messagingSenderId: '15684248875',
    projectId: 'appmovil-8',
    storageBucket: 'appmovil-8.firebasestorage.app',
    iosBundleId: 'com.example.appmovilpractica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsTc5nXkIDyKhdhRn-jVulbJm5afWg4dY',
    appId: '1:15684248875:web:a859221228c2245965d16e',
    messagingSenderId: '15684248875',
    projectId: 'appmovil-8',
    authDomain: 'appmovil-8.firebaseapp.com',
    storageBucket: 'appmovil-8.firebasestorage.app',
    measurementId: 'G-ZHMZBVYEQN',
  );
}
